IMAGES = "/home/images/all/*"
LOGS_DIR = "logs/"
CHECKPOINT = "checkpoint/weights"
USE_CHECKPOINT = True

HR_HEIGHT = 96
HR_WIDTH = 96
r = 2
LR_HEIGHT = HR_HEIGHT // r
LR_WIDTH = HR_WIDTH // r
NUM_CHANNELS = 3
BATCH_SIZE = 32
NUM_PRETRAIN_EPOCHS = 200
NUM_TRAIN_EPOCHS = 150
TRAIN_RATIO = .7
VAL_RATIO = .2
PRETRAIN_ONLY = False

LEARNING_RATE = 1e-4
AD_LOSS_WEIGHT = 10.
BN_EPSILON = 0.001
MOVING_AVERAGE_DECAY = 0.9997
BN_DECAY = MOVING_AVERAGE_DECAY
BETA_1 = 0.9
RANDOM_SEED = 1337 

MAX_FILES = None
PREDICT_ONLY = False
WEIGHTS = None
MEM_FRAC = 0.9
